apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: task-manager
data:
  NODE_ENV: "production"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: task-manager
type: Opaque
stringData:
  # In a real scenario, never commit secrets. Use GitOps/SealedSecrets/ExternalSecrets
  API_KEY: "super-secret-key-123"
  DB_PASSWORD: "simulated-password"
